"""remove orders relationship from customer

Revision ID: 380d70aac27e
Revises: 3d6ba42b4bce
Create Date: 2025-06-04 15:53:12.734434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380d70aac27e'
down_revision: Union[str, None] = '3d6ba42b4bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
