"""add orders relationship to user

Revision ID: 9d9ac05d9bc3
Revises: 822d93a60f2f
Create Date: 2025-06-04 15:54:20.674788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9ac05d9bc3'
down_revision: Union[str, None] = '822d93a60f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
