"""Initial migration

Revision ID: 9f9d00d6a5ab
Revises: 556303a7ecbe
Create Date: 2025-06-03 19:08:17.113724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9d00d6a5ab'
down_revision: Union[str, None] = '556303a7ecbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pizza_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'pizzas', ['pizza_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'pizza_id')
    # ### end Alembic commands ###
