"""Initial migration

Revision ID: efc371f6f0b4
Revises: 9f9d00d6a5ab
Create Date: 2025-06-03 19:09:46.768338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc371f6f0b4'
down_revision: Union[str, None] = '9f9d00d6a5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_pizza_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'pizza_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_pizza_id_fkey', 'orders', 'pizzas', ['pizza_id'], ['id'])
    # ### end Alembic commands ###
