name: Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

env:
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  ALGORITHM: "HS256"
  API_V1_STR: "/api/v1"
  APP_NAME: "Pizza Management System"
  BACKEND_CORS_ORIGINS: '["http://localhost:3000","http://localhost:8080", "https://pizza-management-api-production.up.railway.app"]'
  DEBUG: "True"
  ENVIRONMENT: "development"
  HOST: "0.0.0.0"
  PORT: "8000"
  POSTGRES_DB: "railway"
  POSTGRES_PASSWORD: "yQLRWTiYYkVzZiKpibLyBqmoailuFUuo"
  POSTGRES_PORT: "5432"
  POSTGRES_SERVER: "postgres.railway.internal"
  POSTGRES_USER: "postgres"
  SECRET_KEY: "alavalampitariza"
  DATABASE_URL: "postgresql://postgres:yQLRWTiYYkVzZiKpibLyBqmoailuFUuo@postgres.railway.internal:5432/railway"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        pytest tests/ -v 